"""Build Ren's source-sheet cap and visible ear jewelry; never edit the head.

Run in Blender with --threads 2 --python this_file -- --inspect or --build.
All generated assets remain in the dedicated head-accessories-v1 study folder.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import math
from pathlib import Path
import sys

import bpy
import numpy as np
from mathutils import Vector, Matrix

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT/'art/generated/characters/ren/parts-workflow-v1'
SOURCE = BASE/'face-uv-v1/eye-integration-v2/Ren_P2_Face_EyeUV.blend'
OUT = BASE/'head-accessories-v1'
REFERENCE = ROOT/'art/characters/ren-model-sheet.png'
HAIR_SOURCE = BASE/'ren-shag-v1/trial-v5/Ren_Shag.blend'


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write(name, value):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT/name).write_text(json.dumps(value, indent=2)+'\n', encoding='utf-8')


def signature(obj):
    mesh = obj.data
    result = {'matrix': [list(row) for row in obj.matrix_world]}
    for name, values, dtype in [
        ('vertices', [v.co[:] for v in mesh.vertices], '<f8'),
        ('loops', [v.vertex_index for v in mesh.loops], '<i4'),
        ('polygons', [(v.loop_start, v.loop_total, v.material_index) for v in mesh.polygons], '<i4'),
    ]:
        result[name] = hashlib.sha256(np.array(values, dtype=dtype).tobytes()).hexdigest()
    result['uv'] = {uv.name: hashlib.sha256(np.array([v.uv[:] for v in uv.data], dtype='<f8').tobytes()).hexdigest() for uv in mesh.uv_layers}
    result['shapes'] = {key.name: hashlib.sha256(np.array([v.co[:] for v in key.data], dtype='<f8').tobytes()).hexdigest() for key in mesh.shape_keys.key_blocks} if mesh.shape_keys else {}
    return result


def open_source():
    bpy.ops.wm.open_mainfile(filepath=str(SOURCE))
    return {obj.name: signature(obj) for obj in bpy.context.scene.objects if obj.type == 'MESH'}


def inspect():
    frozen = open_source()
    rows = []
    for obj in bpy.context.scene.objects:
        if obj.type != 'MESH': continue
        coords = np.array([obj.matrix_world@v.co for v in obj.data.vertices])
        rows.append({'name': obj.name, 'vertices': len(coords), 'bounds': [coords.min(axis=0).tolist(), coords.max(axis=0).tolist()], 'hidden': obj.hide_render, 'shapes': [(k.name,k.value) for k in obj.data.shape_keys.key_blocks] if obj.data.shape_keys else [], 'materials': [m.name for m in obj.data.materials]})
        if obj.name == 'Ren_Head':
            np.savez_compressed(OUT/'head-inspection-points.npz', world=coords)
    write('source-inspection.json', {'source': str(SOURCE.relative_to(ROOT)), 'source_sha256': digest(SOURCE), 'objects':rows, 'signatures': frozen})
    print(json.dumps(rows, indent=2), flush=True)


def material(name, srgb, roughness, metal=0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    col = [v/12.92 if v <= .04045 else ((v+.055)/1.055)**2.4 for v in srgb]
    bsdf = mat.node_tree.nodes.get('Principled BSDF')
    bsdf.inputs['Base Color'].default_value = (*col, 1)
    bsdf.inputs['Roughness'].default_value = roughness
    bsdf.inputs['Metallic'].default_value = metal
    mat.diffuse_color = (*col,1)
    return mat


def cap_texture(mat):
    size = 1024
    yy, xx = np.mgrid[0:size,0:size]
    u, v = xx/(size-1), yy/(size-1)
    # Restrained woven-cloth grain, six-panel seam shading and short stitches.
    weave = .0018*(np.sin(xx*2.0)*np.sin(yy*1.7))
    noise = np.random.default_rng(713).normal(0,.0015,(size,size))
    panel = .009*np.cos(u*12*math.pi) + .005*np.sin(v*7)
    base = np.full((size,size), .070)+weave*.4+noise*.4+panel*.5
    crown = (v >= .12)&(v <= .76)
    seam_distance = abs(((u*6+.5)%1)-.5)/6
    base[crown&(seam_distance<.002)] -= .010
    base[crown&(seam_distance>.003)&(seam_distance<.0045)&((v*100)%1<.5)] += .018
    band = (v < .105)
    base[band] -= .012
    base[(abs(v-.125)<.0018)|(abs(v-.745)<.0018)] -= .008
    # Brim uses a distinct atlas strip. Curving is provided by real geometry.
    for row in [.79,.818,.848,.881,.918,.953]:
        base[abs(v-row)<.001] += .013
        base[(abs(v-row)<.00065)&((u*145)%1>.72)] -= .012
    rgb = np.stack((base*.95,base*.95,base*1.05),axis=-1)
    # Tiny irregular embroidered scratch mark, derived from the sheet's small
    # non-lettering emblem; it is not a copied brand or a fabricated word.
    def stroke(a,b,width,col):
        ax,ay=a;bx,by=b
        t=np.clip(((u-ax)*(bx-ax)+(v-ay)*(by-ay))/((bx-ax)**2+(by-ay)**2),0,1)
        d=(u-ax-t*(bx-ax))**2+(v-ay-t*(by-ay))**2
        rgb[d<width*width]=col
    for a,b in [((.928,.268),(.971,.292)),((.937,.25),(.956,.322)),((.947,.25),(.966,.311)),((.93,.29),(.976,.281))]:
        stroke(a,b,.00085,(.32,.32,.35))
    # Generated byte images save their supplied channel values. Keep the file
    # in sRGB; the image texture node performs the sRGB-to-linear conversion.
    rgba = np.dstack((rgb,np.ones((size,size))))
    image = bpy.data.images.new('Ren_Cap_Cloth_BaseColor',width=size,height=size,alpha=True)
    image.pixels.foreach_set(rgba.astype(np.float32).ravel())
    image.filepath_raw = str(OUT/'Ren_Cap_Cloth_BaseColor.png')
    image.file_format = 'PNG'
    image.save()
    # Reopen byte data so Blender, glTF and Unity all interpret the same sRGB
    # file. Generated-image pixels otherwise bypass the loaded image transform.
    bpy.data.images.remove(image)
    image = bpy.data.images.load(str(OUT/'Ren_Cap_Cloth_BaseColor.png'),check_existing=False)
    image.name = 'Ren_Cap_Cloth_BaseColor'
    image.pack()
    texture = mat.node_tree.nodes.new('ShaderNodeTexImage')
    texture.image = image
    mat.node_tree.links.new(texture.outputs['Color'],mat.node_tree.nodes.get('Principled BSDF').inputs['Base Color'])


class Builder:
    def __init__(self): self.vertices=[];self.faces=[];self.uv=[];self.materials=[]
    def vertex(self,p,uv=(0,0)):
        self.vertices.append(tuple(p));self.uv.append(tuple(uv));return len(self.vertices)-1
    def face(self,indices,mat=0):self.faces.append(tuple(indices));self.materials.append(mat)
    def object(self,name,mats,smooth=True):
        used=sorted({index for face in self.faces for index in face})
        remap={old:new for new,old in enumerate(used)}
        self.vertices=[self.vertices[index] for index in used]
        self.uv=[self.uv[index] for index in used]
        self.faces=[tuple(remap[index] for index in face) for face in self.faces]
        mesh=bpy.data.meshes.new(name+'_Mesh')
        mesh.from_pydata(self.vertices,[],self.faces)
        mesh.update()
        ob=bpy.data.objects.new(name,mesh)
        bpy.context.scene.collection.objects.link(ob)
        for mat in mats:mesh.materials.append(mat)
        for polygon,idx in zip(mesh.polygons,self.materials):polygon.material_index=idx;polygon.use_smooth=smooth
        uv=mesh.uv_layers.new(name='AccessoryUV')
        for loop in mesh.loops:uv.data[loop.index].uv=self.uv[loop.vertex_index]
        # Recalculate orientation without changing authored positions or UVs.
        import bmesh
        bm=bmesh.new();bm.from_mesh(mesh);bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bm.to_mesh(mesh);bm.free()
        ob['bind_bone']='Head';ob['default_visible']=True;ob['source_reference']='art/characters/ren-model-sheet.png'
        return ob


CAP_CENTER = Vector((-.035,0,.19))
CAP_ROTATION = (Matrix.Rotation(math.radians(-7),3,'Z') @ Matrix.Rotation(math.radians(3),3,'X') @ Matrix.Rotation(math.radians(3),3,'Y'))


def cap_point(p):return CAP_CENTER+CAP_ROTATION@Vector(p)


def build_cap(cloth, underside):
    b=Builder(); n=28; rings=8
    # Open-bottom six-panel soft crown: geometry only where silhouette needs it.
    for j in range(rings):
        latitude=(j/rings)*math.pi/2
        for i in range(n+1):
            angle=2*math.pi*i/n
            panel=1+.014*math.cos(angle*6)*math.sin(latitude*2)+.005*math.sin(3*angle+latitude*5)
            back_distance=abs((angle-math.pi+math.pi)%(2*math.pi)-math.pi)
            opening=.065*max(0,1-(back_distance/.43)**2)**.5 if j==0 else 0
            asymmetry=math.sin(latitude)**2
            b.vertex(cap_point((.39*math.cos(latitude)*math.cos(angle)*panel-.012*asymmetry,.33*math.cos(latitude)*math.sin(angle)*panel+.007*asymmetry,.38*math.sin(latitude)+opening)), (i/n,.12+.64*j/rings))
    top=b.vertex(cap_point((-.012,.007,.38)),(.5,.76))
    for j in range(rings-1):
        for i in range(n):
            a=j*(n+1)+i;b.face((a,a+1,a+n+2,a+n+1))
    for i in range(n):b.face(((rings-1)*(n+1)+i,(rings-1)*(n+1)+i+1,top))
    # Narrow inside sweat band provides thickness at the visible lower edge.
    base=len(b.vertices)
    for j in range(3):
        for i in range(n+1):
            angle=2*math.pi*i/n
            rx,ry,z=[(.39,.33,0),(.386,.326,-.004),(.376,.316,.029)][j]
            b.vertex(cap_point((rx*math.cos(angle),ry*math.sin(angle),z)),(i/n,j*.045))
    for j in range(2):
        for i in range(n):
            middle=2*math.pi*(i+.5)/n
            if abs(middle-math.pi)<.43:continue
            a=base+j*(n+1)+i;b.face((a,a+1,a+n+2,a+n+1),1)
    # Rear adjustment strap below the real shallow arch opening.
    base=len(b.vertices)
    for z in (0,.018):
        for i in range(5):
            angle=math.pi-.45+.9*i/4
            b.vertex(cap_point((.393*math.cos(angle),.333*math.sin(angle),z)),(i/4,.03))
    for i in range(4):b.face((base+i,base+i+1,base+i+6,base+i+5))
    # Real curved bill, top and underside joined at outer/side boundaries.
    start=len(b.vertices);segments=28;rows=4
    for side in range(2):
        for j in range(rows):
            t=j/(rows-1)
            for i in range(segments+1):
                a=math.radians(-75+150*i/segments)
                x=(.39+.30*t)*math.cos(a)
                y=(.33+.022*t)*math.sin(a)
                z=-.038*t-.055*math.sin(a)**2*t+.003*math.sin(3*a)*t-(.004 if side else 0)
                b.vertex(cap_point((x,y,z)),(i/segments,.78+.19*t))
    slab=rows*(segments+1)
    for side in range(2):
        for j in range(rows-1):
            for i in range(segments):
                a=start+side*slab+j*(segments+1)+i
                b.face((a,a+1,a+segments+2,a+segments+1),side)
    for i in range(segments):
        a=start+(rows-1)*(segments+1)+i;b.face((a,a+1,a+1+slab,a+slab),1)
    for j in range(rows-1):
        for i in (0,segments):
            a=start+j*(segments+1)+i;b.face((a,a+segments+1,a+segments+1+slab,a+slab),1)
    # Low fabric-covered top button, integrated into the cap toggle.
    base=len(b.vertices)
    for j in range(2):
        for i in range(12):
            a=2*math.pi*i/12
            b.vertex(cap_point((-.012+.012*math.cos(a),.007+.012*math.sin(a),.38+j*.006)),(i/12,.05))
    for i in range(12):b.face((base+i,base+(i+1)%12,base+12+(i+1)%12,base+12+i))
    b.face(tuple(base+12+i for i in range(12)))
    return b.object('Ren_Cap',[cloth,underside])


def tube(builder, points, radius=.004, sides=4, closed=True, flat_width=None):
    start=len(builder.vertices);count=len(points)
    for i,p in enumerate(points):
        tangent=Vector(points[(i+1)%count])-Vector(points[(i-1)%count]) if closed else Vector(points[min(i+1,count-1)])-Vector(points[max(i-1,0)])
        tangent.normalize()
        ref=Vector((0,0,1)) if abs(tangent.z)<.8 else Vector((0,1,0))
        u=tangent.cross(ref).normalized();v=tangent.cross(u).normalized()
        for j in range(sides):
            a=2*math.pi*j/sides
            builder.vertex(Vector(p)+radius*math.cos(a)*u+(flat_width or radius)*math.sin(a)*v,(i/max(count-1,1),j/sides))
    for i in range(count if closed else count-1):
        for j in range(sides):builder.face((start+i*sides+j,start+i*sides+(j+1)%sides,start+((i+1)%count)*sides+(j+1)%sides,start+((i+1)%count)*sides+j))
    if not closed:
        builder.face(tuple(start+j for j in reversed(range(sides))))
        builder.face(tuple(start+(count-1)*sides+j for j in range(sides)))


def jewelry(silver,dark):
    b=Builder()
    # Paired narrow helix cuffs: main portrait's exposed anatomical right ear.
    for x,y,z,rx,ry in [(-.118,-.307,.108,.013,.019),(-.129,-.316,.080,.013,.019)]:
        points=[(x+rx*math.cos(a),y+ry*math.sin(a),z) for a in np.linspace(math.radians(-25),math.radians(270),13)]
        tube(b,points,.0038,4,False,flat_width=.005)
    cuff=b.object('Ren_RightEar_HelixCuffs',[silver])
    # A small lobe hoop, angled transverse link and slim open drop frame.
    b=Builder()
    points=[(-.057+.013*math.cos(a),-.294,-.030+.019*math.sin(a)) for a in np.linspace(0,2*math.pi,12,endpoint=False)]
    tube(b,points,.0037,4,True)
    tube(b,[(-.073,-.310,-.035),(-.040,-.313,-.022)],.005,4,False)
    top=Vector((-.059,-.313,-.051))
    profile=[(-.011,0),(.011,0),(.012,-.085),(.005,-.104),(-.005,-.104),(-.012,-.085)]
    tube(b,[(top.x+dx,top.y,top.z+dz) for dx,dz in profile],.0032,4,True)
    drop=b.object('Ren_RightEar_DropPiercing',[silver])
    return [cuff,drop]


def setup_preview():
    scene=bpy.context.scene
    for obj in list(scene.objects):
        if obj.type in {'LIGHT','CAMERA'}:bpy.data.objects.remove(obj,do_unlink=True)
    scene.render.engine='CYCLES'
    scene.cycles.device='CPU';scene.cycles.samples=16
    scene.cycles.use_denoising=True
    scene.render.resolution_x=scene.render.resolution_y=900
    scene.render.resolution_percentage=100
    scene.render.image_settings.file_format='PNG'
    scene.world=bpy.data.worlds.new('Accessories_Review_World');scene.world.use_nodes=True
    scene.world.node_tree.nodes.get('Background').inputs[0].default_value=(.08,.09,.11,1)
    scene.world.node_tree.nodes.get('Background').inputs[1].default_value=.5
    scene.view_settings.view_transform='AgX'
    camera=bpy.data.objects.new('Accessories_Camera',bpy.data.cameras.new('Accessories_Camera'))
    scene.collection.objects.link(camera);scene.camera=camera
    camera.data.type='ORTHO';camera.data.ortho_scale=1.38
    for name,point,power,size in [('Key',(2,-2,3),250,2),('Fill',(2,2,1),150,2),('FaceFill',(3,0,.3),100,2),('Rim',(-2,-1,2),220,1.7)]:
        light=bpy.data.objects.new(name,bpy.data.lights.new(name,'AREA'))
        scene.collection.objects.link(light);light.location=point
        light.rotation_euler=(-light.location).to_track_quat('-Z','Y').to_euler()
        light.data.energy=power;light.data.shape='DISK';light.data.size=size
    return scene


def render(scene,name,angle,target=(.06,0,.045),scale=1.38):
    center=Vector(target);direction=Vector((math.cos(math.radians(angle)),math.sin(math.radians(angle)),.04))
    scene.camera.location=center+direction*3
    scene.camera.rotation_euler=(center-scene.camera.location).to_track_quat('-Z','Y').to_euler()
    scene.camera.data.ortho_scale=scale
    scene.render.filepath=str(OUT/(name+'.png'))
    bpy.ops.render.render(write_still=True)


def build(skip_renders=False):
    before=digest(SOURCE);frozen=open_source()
    cloth=material('Ren_Cap_BlackCloth',(.15,.15,.165),.91)
    cloth.node_tree.nodes.get('Principled BSDF').inputs['Specular IOR Level'].default_value=.08
    cap_texture(cloth)
    underside=material('Ren_Cap_Underside',(.045,.045,.050),.94)
    underside.node_tree.nodes.get('Principled BSDF').inputs['Specular IOR Level'].default_value=.08
    underside.use_backface_culling=True
    silver=material('Ren_Piercing_BrushedSilver',(.72,.75,.82),.29,.86)
    silver.use_backface_culling=True
    dark=material('Ren_Piercing_DarkInset',(.15,.16,.20),.38,.7)
    objects=[build_cap(cloth,underside)]+jewelry(silver,dark)
    for obj in objects:
        obj['part']='cap' if obj.name=='Ren_Cap' else 'ear_jewelry'
        obj['hide_for_face_qa']=obj.name=='Ren_Cap'
        obj['hide_for_contact_qa']=obj.name=='Ren_Cap'
    hair=[]
    if HAIR_SOURCE.is_file():
        with bpy.data.libraries.load(str(HAIR_SOURCE),link=False) as (available,target):
            target.objects=[name for name in available.objects if name.startswith('Ren_Hair_')]
        for obj in target.objects:
            bpy.context.scene.collection.objects.link(obj)
            hair.append(obj)
    scene=setup_preview()
    # Context-only lip material override removes the known draft lipstick.
    # Restore original slots before saving/checking the immutable source meshes.
    head=bpy.data.objects['Ren_Head']
    original_mats=list(head.data.materials)
    for i,mat in enumerate(original_mats):
        if mat.name=='Ren_Draft_RoseLips':head.data.materials[i]=original_mats[0]
    # Required first real combined captures precede extensive export audits.
    if not skip_renders:
        render(scene,'combined-front',0)
        render(scene,'combined-quarter',-35)
        render(scene,'combined-profile',-90)
        render(scene,'jewelry-detail',-70,(-.065,-.29,-.015),.40)
    for i,mat in enumerate(original_mats):head.data.materials[i]=mat
    assert digest(SOURCE)==before
    assert all(signature(bpy.data.objects[name])==sig for name,sig in frozen.items())
    bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'Ren_Head_Accessories_Study.blend'))
    report={'source_blend':str(SOURCE.relative_to(ROOT)),'source_sha256':before,'reference':str(REFERENCE.relative_to(ROOT)),'reference_sha256':digest(REFERENCE),'source_mesh_geometry_uv_shapes_and_matrices_unchanged':True,'coordinates':'+X front, +Z up, original head native units','cap':{'center':list(CAP_CENTER),'rotation_degrees_xyz':[3,3,-7],'radii_xyz':[.39,.33,.38]},'objects':[],'export_status':'pending first visual review','limitations':['Hair fit/fringe visibility pending coordinated combined review.','Jewelry attachment is a fitted study on the current source ear.','No shared rig, skinning, Unity promotion, or device claim.']}
    report['context_hair']={'source':str(HAIR_SOURCE.relative_to(ROOT)),'sha256':digest(HAIR_SOURCE),'objects':[obj.name for obj in hair]} if hair else None
    report['render_only_lip_material_override']='Draft rose lip slot temporarily uses unchanged source skin material; original slots restored before saving.'
    for obj in objects:
        obj.data.calc_loop_triangles()
        p=np.array([obj.matrix_world@v.co for v in obj.data.vertices])
        report['objects'].append({'name':obj.name,'vertices':len(p),'triangles':len(obj.data.loop_triangles),'materials':[m.name for m in obj.data.materials],'bounds':[p.min(0).tolist(),p.max(0).tolist()]})
    report['accessory_triangles']=sum(row['triangles'] for row in report['objects'])
    write('construction.json',report)
    write('fitting-accessories.json',[
        {'path':str((OUT/'Ren_Head_Accessories.blend').relative_to(ROOT)),'objects':['Ren_Cap'],'bind_bone':'Head','default_visible':True,'hide_for_face_qa':True,'hide_for_contact_qa':True},
        {'path':str((OUT/'Ren_Head_Accessories.blend').relative_to(ROOT)),'objects':['Ren_RightEar_HelixCuffs','Ren_RightEar_DropPiercing'],'bind_bone':'Head','default_visible':True,'hide_for_face_qa':False,'hide_for_contact_qa':False}
    ])
    print('REN_ACCESSORIES_FIRST_REVIEW',report['accessory_triangles'],flush=True)


def export_assets(study_name='Ren_Head_Accessories_Study.blend',texture_name='Ren_Cap_Cloth_BaseColor.png'):
    bpy.ops.wm.open_mainfile(filepath=str(OUT/study_name))
    objects=[obj for obj in bpy.context.scene.objects if obj.type=='MESH' and obj.get('part') in {'cap','ear_jewelry'}]
    assert len(objects)==3
    source={}
    for obj in objects:
        obj.data.calc_loop_triangles()
        world=np.array([obj.matrix_world@v.co for v in obj.data.vertices])
        triangles=np.array([t.vertices[:] for t in obj.data.loop_triangles])
        areas=np.linalg.norm(np.cross(world[triangles[:,1]]-world[triangles[:,0]],world[triangles[:,2]]-world[triangles[:,0]]),axis=1)/2
        source[obj.name]={'world':world,'triangles':len(triangles),'min_triangle_area':float(areas.min()),'uv_loops':len(obj.data.uv_layers.active.data)}
        assert np.isfinite(world).all() and areas.min()>1e-12
    bpy.ops.object.select_all(action='DESELECT')
    for obj in objects:obj.select_set(True)
    bpy.context.view_layer.objects.active=objects[0]
    bpy.ops.export_scene.gltf(filepath=str(OUT/'Ren_Head_Accessories.glb'),export_format='GLB',use_selection=True,export_yup=True,export_apply=False,export_extras=True)
    bpy.ops.export_scene.fbx(filepath=str(OUT/'Ren_Head_Accessories.fbx'),use_selection=True,object_types={'MESH'},use_mesh_modifiers=False,bake_anim=False,add_leaf_bones=False,axis_forward='-Z',axis_up='Y',path_mode='COPY',embed_textures=True,use_custom_props=True)
    # Standalone accessory .blend contains the three toggles only, no context.
    for obj in list(bpy.context.scene.objects):
        if obj not in objects:bpy.data.objects.remove(obj,do_unlink=True)
    bpy.ops.wm.save_as_mainfile(filepath=str(OUT/'Ren_Head_Accessories.blend'))
    report={'source_head_sha256':digest(SOURCE),'geometry_built_from':'original Ren designer sheet; local Blender mesh construction, no paid model call','objects':{name:{k:v for k,v in row.items() if k!='world'} for name,row in source.items()},'roundtrips':{}}
    for suffix in ('glb','fbx'):
        bpy.ops.wm.read_factory_settings(use_empty=True)
        path=OUT/('Ren_Head_Accessories.'+suffix)
        if suffix=='glb':bpy.ops.import_scene.gltf(filepath=str(path))
        else:bpy.ops.import_scene.fbx(filepath=str(path),use_anim=False,automatic_bone_orientation=False)
        bpy.context.view_layer.update()
        meshes=[obj for obj in bpy.context.scene.objects if obj.type=='MESH']
        assert {obj.name for obj in meshes}==set(source)
        checks={}
        for obj in meshes:
            obj.data.calc_loop_triangles()
            world=np.array([obj.matrix_world@v.co for v in obj.data.vertices])
            original=source[obj.name]['world']
            distance=np.linalg.norm(world[:,None,:]-original[None,:,:],axis=2)
            error=float(max(distance.min(0).max(),distance.min(1).max()))
            checks[obj.name]={'triangles':len(obj.data.loop_triangles),'render_vertices':len(world),'nearest_vertex_error_native_units':error,'uv_layer_count':len(obj.data.uv_layers),'materials':[mat.name for mat in obj.data.materials]}
            if not (checks[obj.name]['triangles']==source[obj.name]['triangles'] and error<2e-6 and len(obj.data.uv_layers)>=1):
                raise RuntimeError(json.dumps({'format':suffix,'name':obj.name,'actual':checks[obj.name],'expected_triangles':source[obj.name]['triangles']}))
        report['roundtrips'][suffix]={'sha256':digest(path),'objects':checks,'no_armatures':not any(obj.type=='ARMATURE' for obj in bpy.context.scene.objects)}
    report['blend_sha256']=digest(OUT/'Ren_Head_Accessories.blend')
    report['texture_sha256']=digest(OUT/texture_name)
    report['units']='Unnormalized native head units; error values are not world metres.'
    import struct
    data=(OUT/'Ren_Head_Accessories.glb').read_bytes()
    json_size=struct.unpack_from('<I',data,12)[0]
    gltf=json.loads(data[20:20+json_size]);binary=data[28+json_size:]
    view=gltf['bufferViews'][gltf['images'][0]['bufferView']]
    png=binary[view.get('byteOffset',0):view.get('byteOffset',0)+view['byteLength']]
    assert hashlib.sha256(png).hexdigest()==report['texture_sha256']
    report['embedded_glb_texture_exact_png']=True
    report['gltf_materials']=[{'name':m['name'],'double_sided':m.get('doubleSided',False),'pbr':m.get('pbrMetallicRoughness'),'extensions':m.get('extensions',{})} for m in gltf['materials']]
    report['total_accessory_triangles']=sum(row['triangles'] for row in source.values())
    report['limitations']=['Native head units remain unchanged; a later common character normalization is required.','Roundtrips verify static placement/topology/material slots/UV presence, not Unity shader appearance.','No rig or skin weights; all objects provide Head bind metadata.']
    write('export-verification.json',report)
    print('REN_ACCESSORIES_EXPORT_VERIFIED',report['total_accessory_triangles'],flush=True)


def preview_cap():
    bpy.ops.wm.open_mainfile(filepath=str(OUT/'Ren_Head_Accessories_Study.blend'))
    for obj in bpy.context.scene.objects:
        if obj.name.startswith('Ren_Hair_'):obj.hide_render=True
    head=bpy.data.objects['Ren_Head']
    for i,mat in enumerate(head.data.materials):
        if mat.name=='Ren_Draft_RoseLips':head.data.materials[i]=head.data.materials[0]
    render(bpy.context.scene,'cap-fit-quarter',-35)
    render(bpy.context.scene,'cap-fit-rear',180)
    render(bpy.context.scene,'jewelry-fit-detail',-70,(-.065,-.29,-.015),.40)


def main():
    global HAIR_SOURCE
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--inspect', action='store_true')
    parser.add_argument('--build', action='store_true')
    parser.add_argument('--skip-renders', action='store_true')
    parser.add_argument('--export', action='store_true')
    parser.add_argument('--preview-cap', action='store_true')
    parser.add_argument('--hair', type=Path)
    args = parser.parse_args(sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else [])
    OUT.mkdir(parents=True, exist_ok=True)
    if args.hair: HAIR_SOURCE=args.hair if args.hair.is_absolute() else ROOT/args.hair
    if args.inspect: inspect()
    if args.build: build(args.skip_renders)
    if args.export: export_assets()
    if args.preview_cap: preview_cap()


if __name__ == '__main__': main()
